package main

import "strconv"
import "os"
import "fmt"
import "time"
//import "sync"

type Node struct {
  left, right *Node;
  value int;
}

func makeTree(depth int) Node {
  if depth <= 0 {
    return Node{nil, nil, 1};
  } else {
    leftAndRight := makeTree(depth - 1)
    return Node{&leftAndRight, &leftAndRight, 0};
  }
}

// Generate some numbers. (As it happens, the ones from 0..n.)
func generator(n Node) func(func(int) bool) {
  return func(yield func(int) bool) {
    if n.left != nil {
      // fmt.Println("Going left", n.left)
      generator(*n.left)(yield)
    }
    if n.right != nil {
      // fmt.Println("Going right", n.right)
      generator(*n.right)(yield)
    }
    yield(n.value)
  }
}

// Sum up the numbers generated by `generator`.
func sum(n int) int {
  result := 0
  for v := range generator(makeTree(n)) {
    result += v
  }
  return result
}

func main() {
  first, err := strconv.Atoi(os.Args[1])
  if err != nil { panic("arg not parsed as int") }
  last, err := strconv.Atoi(os.Args[2])
  if err != nil { panic("arg not parsed as int") }

  for i := first; i <= last; i++ {
    start := time.Now()
    fmt.Println(sum(i))
    fmt.Println(i)
    fmt.Println("Time: ", time.Since(start));
  }
}
